---
# @var orahost_ssh_keyname:description: >
# The name of used key during role execution.
#
# Example for oracle:
#
# /home/oracle/.ssh/{{ orahost_ssh_keyname }}
# @end
orahost_ssh_keyname: "id_{{ orahost_ssh_key_type }}"
