---
- name: Deploy SSH-Keys on Cluster
  when:
    - _oraswgi_meta_configure_cluster | default(false)
    - inventory_hostname in groups[orasw_meta_cluster_hostgroup]
  block:
    - name: SSH-Keys for {{ oracle_user }}
      ansible.builtin.include_tasks: loop_osuser.yml
      vars:
        _key_owner_home: "{{ oracle_user_home }}"
        _key_owner: "{{ oracle_user }}"
        _key_group: "{{ oracle_group }}"
      when:
        - oracle_databases is defined
        - oracle_databases | selectattr('oracle_db_type','contains','RAC') | length > 0

    - name: SSH-Keys for {{ _grid_install_user }}
      ansible.builtin.include_tasks: loop_osuser.yml
      vars:
        _key_owner_home: "{{ grid_user_home }}"
        _key_owner: "{{ _grid_install_user }}"
        _key_group: "{{ oracle_group }}"
