---

- name: Host configuration
  hosts: "{{ hostgroup | default('all') }}"
  become: true
  any_errors_fatal: true
  roles:
    - opitzconsulting.ansible_oracle.common
    - opitzconsulting.ansible_oracle.orahost
    - opitzconsulting.ansible_oracle.orahost_storage
    - opitzconsulting.ansible_oracle.orahost_ssh
    - opitzconsulting.ansible_oracle.cxoracle
    - opitzconsulting.ansible_oracle.orahost_logrotate
